@extends('layouts.app')
@section('content')
<div class="mb-4"><div class="eyebrow">Administration</div><h1 class="page-title h2 mb-1">Buat akun baru</h1><p class="text-secondary mb-0">Tambahkan akun yang berada dalam kewenangan Anda.</p></div>
<div class="row g-4"><div class="col-xl-8"><div class="panel p-3 p-lg-4"><form method="POST" action="{{ route('users.store') }}">@csrf
<div class="row g-3"><div class="col-md-6"><label class="form-label fw-semibold">Nama lengkap *</label><input class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required>@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-6"><label class="form-label fw-semibold">Email *</label><input class="form-control @error('email') is-invalid @enderror" type="email" name="email" value="{{ old('email') }}" required>@error('email')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="col-md-6"><label class="form-label fw-semibold">Divisi</label><select class="form-select" name="division_id"><option value="">Pilih divisi</option>@foreach($divisions as $division)<option value="{{ $division->id }}" @selected(old('division_id') == $division->id)>{{ $division->name }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label fw-semibold">Tipe akun *</label><select class="form-select" name="role" id="account-role" required>@if($canCreateAdmin)<option value="admin" @selected(old('role', 'admin') === 'admin')>Admin</option>@endif<option value="user" @selected(old('role', $canCreateAdmin ? 'admin' : 'user') === 'user')>User</option></select></div>
<div class="col-12"><div class="row g-3">@if($canCreateAdmin)<div class="col-md-6"><div class="border rounded p-3 h-100"><strong class="d-block"><i class="bi bi-shield-check text-success me-2"></i>Admin</strong><small class="text-secondary">Dapat login dan mengelola aset.</small></div></div>@endif<div class="col-md-6"><div class="border rounded p-3 h-100"><strong class="d-block"><i class="bi bi-person text-success me-2"></i>User</strong><small class="text-secondary">Pemegang aset tanpa akses workspace.</small></div></div></div></div>
<div id="it-password-fields" class="row g-3"><div class="col-md-6"><label class="form-label fw-semibold">Password *</label><input id="new-it-password" class="form-control @error('password') is-invalid @enderror" type="password" name="password">@error('password')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-6"><label class="form-label fw-semibold">Konfirmasi password *</label><input id="confirm-it-password" class="form-control" type="password" name="password_confirmation"></div></div><div id="user-password-note" class="col-12 d-none"><div class="alert alert-light border mb-0"><i class="bi bi-info-circle me-2"></i>User tidak memerlukan password karena tidak dapat mengakses workspace.</div></div></div>
<div class="d-flex justify-content-end mt-4 pt-3 border-top"><button class="btn btn-primary"><i class="bi bi-person-plus me-2"></i>Buat akun</button></div></form></div></div><div class="col-xl-4"><div class="panel p-3 p-lg-4"><div class="asset-icon mb-3"><i class="bi bi-shield-check"></i></div><h2 class="h5">Kontrol akses</h2><p class="text-secondary small mb-0">{{ $canCreateAdmin ? 'Super Admin dapat membuat akun Admin atau User.' : 'Admin hanya dapat membuat akun User.' }} User tetap dapat dipilih sebagai pemegang aset.</p></div></div></div>
<script>const roleSelect=document.getElementById('account-role');const syncPasswordFields=()=>{const admin=roleSelect.value==='admin';document.getElementById('it-password-fields').classList.toggle('d-none',!admin);document.getElementById('user-password-note').classList.toggle('d-none',admin);document.getElementById('new-it-password').required=admin;document.getElementById('confirm-it-password').required=admin;};roleSelect.addEventListener('change',syncPasswordFields);syncPasswordFields();</script>
@endsection
